### ISSUE TITLE
Bug: Booleans from Forms stored as "1" or "0"

### ISSUE THREAD

**Issue by mscoutermarsh** [G5/storext#16]
Noticing that Boolean values when updated from a Rails form are being stored as "1" or "0" instead of true/false.

**More Info:**

```Ruby
example_setting Boolean, default: true
```

If I set `example_setting` from a console. `object.example_setting = true`. It is stored correctly.

`{ "example_setting": true }`

But if I submit it from a Rails form (which uses 1 or 0 for true/false).

`{ "example_setting": "1" }`

This still works as expected & doesn't cause any problems. But I think it would be best if 1's and 0's are translated to true/false for consistency.

Note: I'm using JSONB for my storeaccessor.

**Comment by mscoutermarsh** [comment]
Btw: Of course, I'm happy to do a PR to help out with this. :smile:

**Comment by ramontayag** [comment]
Yeah sure why not?
