### ISSUE TITLE
Methods like _was, _changed? are not working

### ISSUE THREAD

**Issue by stebo** [G5/storext#28]
With storext the methods from ActiveRecord::Dirty like attribute_was, attribute_changed? do not work properly on attributes which are initialized with store_attributes:

```ruby
book.title
=> "Great Voyage"
book.title = "New Title"
=> "New Title"
book.title_was
=> "New Title"
book.title_changed?
=> false
```

Especially for validations with if conditions this would be very important.

Any ideas where in the code this could be added/fixed?

**Comment by ramontayag** [comment]
Since it just uses AR::Store underneath, I think the changes should be made
there. That way, users of AR::Store benefit as well.

I did a quick search, and it looks like others have asked for it.

https://github.com/rails/rails/issues/16808

**Comment by ramontayag** [comment]
I'm going to close this. While this would be a great feature to have, it feels like it shouldn't be on Storext, but in `ActiveRecord::Store` itself.
