### ISSUE TITLE
Use with Ransack

### ISSUE THREAD

**Issue by michaelminter** [G5/storext#44]
Has anyone figured out how to use Storext with Ransack search features?

**Comment by ramontayag** [comment]
Haven't tried. Don't see why you couldn't do this though. If you're just using hstore, json, or jsonb underneath, then you can use PG querying syntax: http://schinckel.net/2014/05/25/querying-json-in-postgres/

**Comment by ramontayag** [comment]
Will close this. Feel free to reopen with updates
