### ISSUE TITLE
Can't dump anonymous class if default value not set.

### ISSUE THREAD

**Issue by gcrofils** [G5/storext#47]
# Summary

`Marshal.dump` fails on any object if default value is not defined for Jsonb attributes

# Steps to replicate

1. New Rails app `rails new storext-demo --api`
2. Add `pg` gem, add `storext`gem
3. create model *with* default value
  * `rails g model book title:string data:jsonb`
```
class Book < ApplicationRecord
  include Storext.model
  store_attributes :data do
    sync Boolean, default: true
    sync_at DateTime, default: 0
  end
end
```
4. create model *without* default value
  * `rails g model post title:string data:jsonb`
 ``` 
class Post < ApplicationRecord
  include Storext.model
  
  store_attributes :data do
    sync Boolean
    sync_at DateTime
  end
  
end
```

5. `Marshal.dump` works on model *with* default value
  * `Book.create title:'Lorem Ipsum'`
  * `Marshal.dump Book.first` ==> OK

6. `Marshal.dump` fails on model *without* default value
  * `Post.create title:'Lorem Ipsum'`
  * `Marshal.dump Post.first` ==> KO `TypeError: can't dump anonymous class #<Class:0x007fefcdab1340>`

**Comment by ramontayag** [comment]
@gcrofils when writing, Storext just uses `ActiveRecord::Store` underneath. Are you able to do what you want with `ActiveRecord::Store`?

**Comment by gcrofils** [comment]
I don't fully understand your question "Are you able to do what you want with `ActiveRecord::Store`?".
 
`Marshal.dump` fails if there is no value for an attribute with `TypeError: can't dump anonymous class`. 

It works in other cases, either if there is a default value (defined in `store_attributes`) or a value set. 

Hence if you try to `Marshal.dump` a record with a `stored attribute` that is `nil`, it will fail if this attribute has no default value.

**Comment by ramontayag** [comment]
Ok that's right. Storext uses anonymous classes in which it defines Virtus attributes. The values go through an instance of that class and that instance that has Virtus does a lot of the typecasting/conversion. I'm not familiar with `Marshal` and don't really understand what it means when it says it will dump [descendant objects](https://ruby-doc.org/core-2.2.2/Marshal.html#method-c-dump).

**Comment by ramontayag** [comment]
The fix might be somewhere [here](https://ruby-doc.org/core-2.5.0/Marshal.html#module-Marshal-label-marshal_dump+and+marshal_load) where `marshal_dump` and `marshal_load` are defined.

**Comment by topherfangio** [comment]
So, the issue lies here:

```ruby
def storext_proxy_class
  Storext.proxy_classes[self] ||= Class.new(*Storext.proxy_classes[self.superclass]) do
    include Virtus.model
    attribute :source
  end
end
```

`Marshal.dump` just doesn't know how to dump the `Class.new`.

We were able to monkey patch this with the following code.

```ruby
module Storext
  module ClassMethods
    class Dumpable
      include Virtus.model
      attribute :source
    end
    
    def storext_proxy_class
      Storext.proxy_classes[self] ||= Dumpable
    end
  end
end
```

But I'm pretty sure this exists to cover cases of a parent class that uses Storext as well as it's child class using Storext, so this could easily break stuff for us later on down the road. Not sure if there is another workaround, but we couldn't figure out how to use the `Marshal` methods to get it working.

**Comment by ramontayag** [comment]
Thanks. This'll be helpful. Mind writing a failing test case? I'll see what I can do :)

**Comment by ramontayag** [comment]
Right now all tests are failing in Travis, but you should be able to run it locally. I'm currently trying to fix the tests in Travis.

**Comment by seattlecyclist** [comment]
@ramontayag - With regard to the error @topherfangio reported.  I work with him. Here is a failing spec.  Just drop it into your `storext_spec.rb` and run it.
```
  it "can properly marshal" do
    author = Author.new(name: "A. Clarke")
    expect{Marshal.dump(author)}.to_not raise_exception(TypeError)
  end
```

**Comment by ramontayag** [comment]
@seattlecyclist will https://github.com/G5/storext/pull/56 work for you?
