### ISSUE TITLE
Boolean type not recognized when using store_attributes inside concern

### ISSUE THREAD

**Issue by radubogdan** [G5/storext#48]
Hello again,

I noticed I get errors if I move store_attributes in a concern and use the Boolean type.

```
module CarLeasing
  extend ActiveSupport::Concern

  included do

    store_attributes :leasing_offer do
      leasing_has_rest_debt Boolean
    end

  end
end
```

```
pry(main)> Car.storext_definitions
NameError: uninitialized constant CarLeasing::Boolean
```

However inside the model which includes this concern everything works:

```
{:leasing_has_rest_debt=>{:column=>:leasing_offer, :type=>Axiom::Types::Boolean (BasicObject), :opts=>{}}}
```

Is it not suitable to use concerns together with storext? 

Thanks!

**Comment by ramontayag** [comment]
@radubogdan yup that's because Boolean is a Virtus constant that it can't find when importing it from a concern.

The fix would be somewhere [here](https://github.com/G5/storext/blob/8cf6711e5d753f469516db92f1fd9865a9a35606/lib/storext.rb#L43).

**Comment by ramontayag** [comment]
@radubogdan I'll close this. I'd be happy to get a pull request!

**Comment by NomNomCameron** [comment]
in case anyone else runs into this,  here's how I solved this:

```rb
included do |base|
  store_attributes :settings do
    setting_field base::Boolean, default: false
  end
end
