### ISSUE TITLE
Empty string is converted to nil automatically

### ISSUE THREAD

**Issue by ldlgds2** [G5/storext#49]
When extracting data from JSONb where the values are the empty string, e.g. "", the gem will return them as nil into Rails.

**Comment by ramontayag** [comment]
@ldlgds2, ok it should return them as blank strings too, I agree.

**Comment by ramontayag** [comment]
I couldn't replicate the issue in a spec. Please see `jsonb-blank-string-49` branch

**Comment by ldlgds2** [comment]
@ramontayag : Maraming salamat po :)
I will check with my former team another time and get back to you ASAP about this issue. Maybe there also was a DB or gem conflict issue.
