### ISSUE TITLE
nested ActiveModel objects

### ISSUE THREAD

**Issue by ditsara** [G5/storext#55]
I've found this gem to be really useful, but I often want to store nested data. I have a monkey patch for storing ActiveModel-compatible objects that I've been passing around among various projects. Would you accept a pull request to integrate this directly into the gem?

**Comment by ramontayag** [comment]
How would they be stored in the db?

**Comment by ditsara** [comment]
As a hash or array of hashes.

For example:

```ruby
{
  address_attributes: {
    name: "Joe"
    address1: "123 Main St"
    city: "Ann Arbor"
    state: "MI"
    postal_code: "12345-6789"
  }
}
```
Would basically be instantiated using:

```ruby
class Address
  include ActiveModel::Model
  attr_accessor :name, :address1, :etc
end
```

**Comment by maysam** [comment]
> As a hash or array of hashes.
> 
> For example:
> 
> ```ruby
> {
>   address_attributes: {
>     name: "Joe"
>     address1: "123 Main St"
>     city: "Ann Arbor"
>     state: "MI"
>     postal_code: "12345-6789"
>   }
> }
> ```
> 
> Would basically be instantiated using:
> 
> ```ruby
> class Address
>   include ActiveModel::Model
>   attr_accessor :name, :address1, :etc
> end
> ```

How do you use it? is there a code somewhere I can see it in action?

**Comment by ramontayag** [comment]
Just cleaning up -- closing this.

Reading it again, yes I second @maysam's question. Let's see a valid use-case before merging it in. In the scenario you posted, I would've just made another `Address` model.
