### ISSUE TITLE
define conditional attributes

### ISSUE THREAD

**Issue by tomkra** [G5/storext#63]
Hello,

is there any way to define conditional attributes? I need to do something like this:
```ruby
class MyModel < ApplicationRecord
  include Storext.model

  enum model_type: { basic: 1, better: 2 }

  store_attributes :settings do
    setting_1 Boolean, default: false, if: proc { |m| m.basic? }
    setting_2 Boolean, default: false, if: proc { |m| m.better? }
  end
end
```

How can I achieve this? Thank you.

**Comment by ramontayag** [comment]
There's none, but if you want that I think you should go for STI. You'll have a `BasicModel` with `setting_1` and `BetterModel` with `setting_2`.

**Comment by tomkra** [comment]
@ramontayag Thank you, this should solve my issue :).
